/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabinetmedicalpsbd;

import java.awt.Toolkit;

/**
 *
 * @author Maria
 */
public class NouNascuti extends javax.swing.JFrame {

    /**
     * Creates new form NouNascuti
     */
    public NouNascuti() {
        initComponents();
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        
        
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getWidth();
       this.setSize(xsize, ysize); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Acasa = new javax.swing.JButton();
        InapoiButon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/hiperdia.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        Acasa.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Acasa.setForeground(new java.awt.Color(0, 0, 153));
        Acasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/med.jpg"))); // NOI18N
        Acasa.setText("Acasa");
        Acasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcasaActionPerformed(evt);
            }
        });
        getContentPane().add(Acasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 140, 50));

        InapoiButon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        InapoiButon.setForeground(new java.awt.Color(0, 0, 51));
        InapoiButon.setText("Inapoi");
        InapoiButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InapoiButonActionPerformed(evt);
            }
        });
        getContentPane().add(InapoiButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedicalpsbd/fundal2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcasaActionPerformed
        Main m = new Main();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_AcasaActionPerformed

    private void InapoiButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InapoiButonActionPerformed
        PacientiCRUD m = new PacientiCRUD();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_InapoiButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NouNascuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NouNascuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NouNascuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NouNascuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NouNascuti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acasa;
    private javax.swing.JButton InapoiButon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
